production:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
staging:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
local:
  host: 127.0.0.1:33060
  database: db_name
  username: homestead
  password: 'secret'